// Code generated by "stringer -type=Month"; DO NOT EDIT.

package module

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[January-1]
	_ = x[February-2]
	_ = x[March-3]
	_ = x[April-4]
	_ = x[May-5]
	_ = x[June-6]
	_ = x[July-7]
	_ = x[August-8]
	_ = x[September-9]
	_ = x[October-10]
	_ = x[November-11]
	_ = x[December-12]
}

const _Month_name = "JanuaryFebruaryMarchAprilMayJuneJulyAugustSeptemberOctoberNovemberDecember"

var _Month_index = [...]uint8{0, 7, 15, 20, 25, 28, 32, 36, 42, 51, 58, 66, 74}

func (i Month) String() string {
	i -= 1
	if i < 0 || i >= Month(len(_Month_index)-1) {
		return "Month(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Month_name[_Month_index[i]:_Month_index[i+1]]
}
